---
title: "Descriptive Statistics"
subtitle: "Phthalates & phenols in M&N cohort"
author: "Lizzy Gibson"
date: "3/5/2021"
output:
  html_document:
    toc: yes
    toc_float: yes
    code_folding: 'hide'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align='center')

source("./packages.R")
source("./read_data.R")
```

### Patterns

```{r, fig22}
ewa %>% 
  pivot_longer(P1:P2) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(y = ..density..), alpha=0.65, fill = "#0072B5") +
  facet_wrap(name~., scales = "free") + 
  labs(y = "Density", x="") +
  theme(axis.text.y = element_blank(),
        text = element_text(size = 30),
        axis.text.x = element_text(size = 10),
        axis.title.y = element_text(size = 30))

bind_cols(ppp_current, ewa) %>% 
  mutate(SEX = fct_relevel(SEX, "Male", after = 1)) %>% 
  pivot_longer(P1:P2) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(y = ..density.., fill = SEX), alpha = 0.65, position = "identity") +
  facet_wrap(name~., scales = "free") + 
  labs(y = "Density", x="") +
  theme(axis.text.y = element_blank(),
        text = element_text(size = 30),
        axis.text.x = element_text(size = 10),
        axis.title.y = element_text(size = 30))
```

## Correlation

```{r, fig.height=7, fig.width=7}
cormat <- get_lower_tri(round(cor(mn_ppp[,-1], use = "complete.obs", 
                                  method = c("spearman")),2))[2:17, 1:16]

melted_cormat <- melt(cormat) %>% 
  rename(Correlation = value) %>% 
  mutate(Var1 = case_when(Var1 == "DCP_24" ~ "24-DCP",
                          Var1 == "DCP_25" ~ "25-DCP",
                          Var1 == "BP_3" ~ "BP-3",
                          TRUE ~ as.character(Var1)),
         Var2 = case_when(Var2 == "DCP_24" ~ "24-DCP",
                          Var2 == "DCP_25" ~ "25-DCP",
                          Var2 == "BP_3" ~ "BP-3",
                          TRUE ~ as.character(Var2)),
    Var1 = fct_inorder(str_remove(Var1, "_")),
    Var2 = fct_inorder(str_remove(Var2, "_"))) %>% as_tibble()

#pdf("./Figures/ppp_corr.pdf")
melted_cormat %>% 
  mutate(Var1 = fct_rev(Var1)) %>% 
  ggplot(aes(x = Var2, y = Var1)) + 
  geom_tile(aes(fill = Correlation), color = "black", size=0.25) + 
  scale_fill_gradient2(low = "#046C9A", mid = "beige", high = "#F21A00",
                       na.value = "grey90") +
  #scale_fill_distiller(palette="RdYlBu",
  #                     na.value = "grey90") +
  labs(x = "", y = "", title = "") + 
  theme_test(base_size = 20) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 15),
        legend.position = "bottom")
#dev.off()
```

## Loadings

```{r}
applied <- eh %>% 
  as_tibble() %>% 
  mutate(Pattern = 1:2) %>% 
  gather(key = Chemicals, value = Loadings, -Pattern) %>%
  mutate(Class = as_factor(case_when(grepl("PB", Chemicals) ~ "Parabens",
                           grepl("^M[A-Z]", Chemicals) ~ "Phthalates",
                           TRUE ~ "Phenols")),
         Chemicals = str_replace(Chemicals, "_", "-")) %>% 
  mutate(Pattern = paste0("Pattern ", Pattern),
         Chemicals = fct_inorder(Chemicals))

#44pdf("./Figures/eh_loadings.pdf", width = 2.5)
applied %>% 
  mutate(Chemicals = fct_rev(Chemicals)) %>% 
  ggplot(aes(x = Pattern, y = Chemicals)) + 
  geom_tile(aes(fill = Loadings), color = "black", size=.25) + 
  scale_fill_gradient2(low = "#046C9A", mid = "beige", high = "#F21A00") +
  labs(x = "", y = "", title = "") + 
  theme_test(base_size = 20) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 15),
        panel.grid.major = element_blank(),
        legend.direction = "horizontal",
        legend.position = c(0, -0.275), # c(1,0) right bottom, c(1,1) right top.
        legend.background = element_rect(fill = "#ffffffaa", colour = NA),
        #legend.key.size = unit(0.85, "lines"),
        plot.margin = margin(0,1,1,0, "cm"))
#dev.off()
```

### Chemicals with patterns

```{r, fig.width=3, fig.height=7}
chem_pat = bind_cols(mn_ppp, ewa) %>% dplyr::select(-SID) %>% as.matrix()

cormat_p <- get_lower_tri(round(cor(chem_pat, use = "complete.obs", 
                                  method = c("spearman")),2))[18:19,]

melted_cormat_p <- melt(cormat_p) %>% 
  rename(Correlation = value) %>% 
  mutate(Var1 = str_replace(Var1, "_", "-"),
    Var1 = fct_inorder(Var1),
    Var2 = str_replace(Var2, "_", "-"),
    Var2 = fct_inorder(Var2)) %>% 
  filter(!(Var2 %in% c("P2","P1")))

ggplot(data = melted_cormat_p, aes(x = Var1, y = Var2)) + 
  geom_tile(aes(fill = Correlation), color = "white") + 
  scale_fill_gradient2(low = "#046C9A", mid = "beige", high = "#F21A00") +
  #scale_fill_gradientn(colors=cols, limits = c(-1,1),
  #                     na.value = "grey80") +
  labs(x = "", y = "", title = "") + 
  theme_test(base_size = 20) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.text = element_text(size = 10),
        legend.position = "bottom")
```

## Extreme values

```{r}
#bind_cols(mn_ppp, ewa) %>% filter(P2 > 30) %>% select(SID, P1, P2, everything())
  
extreme = bind_cols(mn_ppp, ewa) %>% filter(P2 > 30) %>%
  t() %>% as.data.frame() %>% rownames_to_column(var = "Chemical") %>% 
  mutate_at(vars(2:4), as.numeric) %>% 
  filter(Chemical != "SID")
```

```{r, figend, fig.height=10, fig.width=12}
mn_ppp %>%
  pivot_longer(MEHHP:BPA,
               names_to = "Chemical") %>% 
  left_join(., extreme) %>% 
  filter(grepl("^M", Chemical) | Chemical == "BPA") %>%
  filter(!(Chemical %in% c("MEP", "M_PB"))) %>% 
  mutate(Chemical = str_replace(Chemical, "_", "-")) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(y = ..density..), fill = "#0072B5", alpha=0.75) +
  geom_vline(aes(xintercept = V1), linetype = "dashed", color = "#E18727") + 
  geom_vline(aes(xintercept = V2), linetype = "dashed", color = "#20854E") + 
  geom_vline(aes(xintercept = V3), linetype = "dashed", color = "#F21A00") + 
  facet_wrap(Chemical~., scales = "free") + 
  labs(y = "Density", x="") +
  theme(axis.text.y = element_blank(),
        text = element_text(size = 30),
        axis.text.x = element_text(size = 10),
        axis.title.y = element_text(size = 35))
```

