---
title: "Bayesian models with Gamma*Gamma distributions"
subtitle: "& comparison with Normal approximation"
author: "Lizzy Gibson"
date: "4/13/2021"
output:
  html_document:
    toc: yes
    toc_float: yes
    code_folding: 'hide'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align='center', cache=TRUE,
                      autodep = TRUE)
options(scipen = 999)
library(haven)
library(tidyverse)
library(RColorBrewer)
library(mgcv)
library(janitor)
library(gt)
library(reshape2)
library(broom)
library(tableone)
library(xtable)
library(GGally)
library(gtsummary)
library(huxtable)
library(rcompanion)
library(R.matlab)
library(MNdata) # Local package
library(ggsci)
library(patchwork)
library(rstan)
library(bayesplot)
library(shinystan)
library(rstanarm)
library(tictoc)
library(recipes)
library(ggridges)
library(bayestestR)

options(mc.cores = parallel::detectCores())

# theme_set(theme_bw(base_size = 20) + 
#             theme(strip.background = element_rect(fill="white"),
#                   axis.text.x = element_text(angle = 45, hjust = 1),
#                   legend.title = element_text(size = 12),
#                   legend.position = "bottom", 
#                   legend.text = element_text(size = 7)))
# 
# options(
#   ggplot2.discrete.color = pal_nejm()(8),
#   ggplot2.discrete.fill = pal_nejm()(8))
```

```{r, functions}
# Get lower triangle of the correlation matrix
get_lower_tri<-function(x){
  x[upper.tri(x)] <- NA
  
  for (i in 1:nrow(x)) {
    for (j in 1:ncol(x)) {
      if (j == i) {x[i,j] <- NA}
    }
  }
  
  return(x)
}

tidy_ci = function(fit) {
              tidy(fit) %>% bind_cols(., as_tibble(confint(fit)))
}

add_ci4interaction <- function(fit, term1, term2) {
    # CONFIDENCE INTERVAL for pattern in females
    # Compute association and its uncertainty 
    
    # here we create tables of coefficients and covariance
    coef.mat <- summary(fit)$coefficients
    var.mat  <- vcov(fit)
    
    # the total term for the association is the 
    # sum of P2 in the reference sex plus the term for P2:female
    beta.Pf <- coef.mat[term1,1] + coef.mat[term2,1]
    
    # Compute variance in order to compute standard error
    # We must compute the variance for the total term 
    # Var(Beta1 + Beta2) = Var(Beta1) + Var(Beta2) + 2*CoVar(Beta1, Beta2) 
    var.Pf <- var.mat[term1, term1] + 
              var.mat[term2, term2] +
              2*var.mat[term1, term2]
    
    # this is st error NOT std
    ste.Pf  <-  sqrt(abs(var.Pf))

    # compute confidence intervals 
    lci.Pf <- beta.Pf - 1.96*ste.Pf
    uci.Pf <- beta.Pf + 1.96*ste.Pf
    
    # 2 calculate the test statistic: t = Est/SE
    # 3 calculate the P value2: P = exp(−0.717×z − 0.416×z2).
    test_stat = abs(beta.Pf/ste.Pf)
    pvalue = exp(-0.717*test_stat - 0.416*test_stat^2)
    pvalue
    
    tidy_ci(fit) %>% 
      bind_rows(., tibble(term = paste0(term1, " in females"), estimate = beta.Pf, std.error = ste.Pf,
                statistic = test_stat, p.value = pvalue, `2.5 %` = lci.Pf, `97.5 %` = uci.Pf)) %>% 
      mutate(term = ifelse(term == term1, paste(term1, "in males"), term))
}

add_ci4int_bayes = function(fit) {
int_sum = summary(fit, c("beta_int", "beta_sex", "beta_p"))$summary

params = names(p1_gamma_un)[grep("(alpha|beta)", names(p1_gamma_un))]
model_sum = summary(fit, params)$summary

ext <- extract(fit)

post_coef = cbind(ext$alpha, ext$beta_c, 
                     ext$beta_int, ext$beta_sex, ext$beta_p) %>% as_tibble()

colnames(post_coef) = params
int_coefs = post_coef %>% dplyr::select(beta_p, beta_int)

coef1 = int_coefs$beta_p
coef2 = int_coefs$beta_int

covmat = cov(int_coefs)
beta_f = coef1 + coef2

var_f = covmat[1, 1] + 
              covmat[2, 2] +
              2*covmat[1, 2]

# this is std dev not std error
sd_f  <- sqrt(abs(var_f))

# take min sample size as conservative est.
sampsize = min(int_sum[1,9], int_sum[3,9])

# this is std error
se_f  <- sd_f/sqrt(sampsize)

lci.f <- mean(beta_f) - 1.96*se_f
uci.f <- mean(beta_f) + 1.96*se_f

# 2 calculate the test statistic: t = Est/SE
# 3 calculate the P value2: P = exp(−0.717×z − 0.416×z2).
# test_stat = abs(mean(beta_f)/se_f)
# pvalue = exp(-0.717*test_stat - 0.416*test_stat^2)
# NO BAYESIAN PVALUE

q = quantile(beta_f, probs = c(0.025, .25, .50, .75, .975)) %>% as.data.frame() %>% 
  rownames_to_column() %>% 
  pivot_wider(names_from = "rowname",
              values_from = ".")

new_var = tibble(beta = "p in females", mean = round(mean(beta_f), 4), 
                 se_mean = round(se_f,4), sd = round(sd_f,4)) %>% 
          bind_cols(., q)

# M_AGE + M_EDU + MARITAL_STATUS + HOME_SCORE + M_IQ + ALCOHOL + mat_hard, 
as.data.frame(model_sum)[,-c(9:10)] %>% 
  rownames_to_column(var="beta") %>% 
  mutate(beta = c("alpha", "age", "edu", "marital", "home", "iq", "alcohol", "mat_hard",
                  "sex*p", "sex", "p in males")) %>% 
  bind_rows(.,new_var) %>% 
  mutate_at(vars(2:9), round, 2)
}
```

## Mothers & Newborns

* 5 phenols  
* 3 parabens  
* 9 phthalates  

```{r, dat}
# UNSTANDARDIZED NORMAL
e_wa_un <- readMat(here::here("./Data/mn2_EWA_un.mat"))[[1]] %>% as_tibble() %>% rename(P1 = V1, P2 = V2)
var_wa_un <- readMat(here::here("./Data/mn2_WA_var_un.mat"))[[1]] %>% as_tibble() %>% rename(varP1 = V1, varP2 = V2)

# STANDARDIZED NORMAL
e_wa <- readMat(here::here("./Data/mn2_EWA_sd1.mat"))[[1]] %>% as_tibble() %>% rename(P1_scaled = V1, P2_scaled = V2)
var_wa <- readMat(here::here("./Data/mn2_WA_var_sd1.mat"))[[1]] %>% as_tibble() %>% rename(varP1_scaled = V1, varP2_scaled = V2)

# UNSTANDARDIZED GAMMA*GAMMA
alpha_w <- readMat(here::here("./Data/mn2_Walpha.mat"))[[1]] %>% as_tibble() %>% rename(walpha1 = V1, walpha2 = V2)
beta_w <- readMat(here::here("./Data/mn2_Wbeta.mat"))[[1]] %>% as_tibble() %>% rename(wbeta1 = V1, wbeta2 = V2)

alpha_a <- readMat(here::here("./Data/mn2_Aalpha.mat"))[[1]] %>% as_tibble() %>% rename(aalpha1 = V1, aalpha2 = V2)
beta_a <- readMat(here::here("./Data/mn2_Abeta.mat"))[[1]] %>% as_tibble() %>% rename(abeta1 = V1, abeta2 = V2)

bayes = bind_cols(ppp_cov, e_wa, var_wa, e_wa_un, var_wa_un, alpha_w, beta_w) %>% 
        dplyr::select(-GEST, -ETH) %>% 
        rename(HOME_SCORE = HOMETOT) %>% 
        filter(P1 != max(P1)) %>%
        filter(P1 != max(P1)) %>%  # removes two females, 1 male
        drop_na() %>% 
        mutate_at(vars(c(HOME_SCORE, M_AGE, M_IQ)), scale) %>% 
        mutate_if(is.character, as_factor)

# For stan model ####
N = nrow(bayes)
C = 7 # number of covariates
x = model.matrix(WISC ~ M_AGE + M_EDU + MARITAL_STATUS + HOME_SCORE + M_IQ + ALCOHOL + mat_hard, 
                 data = bayes)[,-1]
sex = model.matrix(WISC ~ SEX, data = bayes)[,-1]
y = bayes$WISC

# Predictors of interest change
```

### Unscaled
```{r, dat3}
# Normal
P1_un = bayes$P1
sd_ewa_un = bayes%>% dplyr::select(varP1, varP2) %>% mutate_all(~sqrt(.))
sdP1_un = sd_ewa_un$varP1

# Gamma
Walpha1_un = bayes$walpha1
Wbeta1_un  = bayes$wbeta1

Aalpha1_un = alpha_a[[1]]
Abeta1_un  = beta_a[[1]]
```

### Standardized
```{r, dat2}
# Normal
P1_sc = bayes$P1_scaled
sd_ewa_sc = bayes %>% dplyr::select(varP1_scaled, varP2_scaled) %>% mutate_all(~sqrt(.))
sdP1_sc = sd_ewa_sc$varP1_scaled

# Gamma
#Walpha1_sc = bayes$walpha1 # don't scale alpha, only scale beta
Wbeta1_sc  = (bayes$wbeta1/17.3043)*4.4074

# Aalpha1_sc = alpha_a[[1]] # don't scale alpha, only scale beta
Abeta1_sc  = (beta_a[[1]]/17.3043)*4.4074
```

*Just for pattern 1 for now*  

```{r, standat}
p1_norm_un_dat = list(N = N,
                  C = C,
                  x = x,
                  y = y,
                  sex = sex,
                  ewa = P1_un,
                  sd_ewa = sdP1_un)

p1_gamma_un_dat = list(N = N,
                  C = C,
                  x = x,
                  y = y,
                  sex = sex,
                  alpha_w = Walpha1_un,
                  beta_w = Wbeta1_un,
                  alpha_a = Aalpha1_un,
                  beta_a = Abeta1_un)

p1_norm_scaled_dat = list(N = N,
                  C = C,
                  x = x,
                  y = y,
                  sex = sex,
                  ewa = P1_sc,
                  sd_ewa = sdP1_sc)

p1_gamma_scaled_dat = list(N = N,
                  C = C,
                  x = x,
                  y = y,
                  sex = sex,
                  alpha_w = Walpha1_un,
                  beta_w = Wbeta1_sc,
                  alpha_a = Aalpha1_un,
                  beta_a = Abeta1_un)
```

## Bayesian models

```{r}

p1_gamma_scaled <- stan(
  file = "./Stan/models/bn2mf_score_reg_int_gamma.stan",  # Stan program
    data = p1_gamma_scaled_dat,               # named list of data
    chains = 4,                   # number of Markov chains
    warmup = 1000,                # number of warmup iterations per chain
    iter = 5000,                  # total number of iterations per chain
    cores = 2)                    # number of cores
save(p1_gamma_scaled, file = "./Stan/fits/pattern1_gamma_scaled.rda")

p1_norm_scaled <- stan(
  file = "./Stan/models/bn2mf_score_reg_int.stan",  # Stan program
    data = p1_norm_scaled_dat,               # named list of data
    chains = 4,                   # number of Markov chains
    warmup = 1000,                # number of warmup iterations per chain
    iter = 5000,                  # total number of iterations per chain
    cores = 2)                    # number of cores
save(p1_norm_scaled, file = "./Stan/fits/pattern1_norm_scaled.rda")

p1_gamma_un <- stan(
  file = "./Stan/models/bn2mf_score_reg_int_gamma.stan",  # Stan program
    data = p1_gamma_un_dat,               # named list of data
    chains = 4,                   # number of Markov chains
    warmup = 1000,                # number of warmup iterations per chain
    iter = 5000,                  # total number of iterations per chain
    cores = 2)                    # number of cores
save(p1_gamma_un, file = "./Stan/fits/pattern1_gamma_un.rda")

p1_norm_un <- stan(
  file = "./Stan/models/bn2mf_score_reg_int.stan",  # Stan program
    data = p1_norm_un_dat,               # named list of data
    chains = 4,                   # number of Markov chains
    warmup = 1000,                # number of warmup iterations per chain
    iter = 5000,                  # total number of iterations per chain
    cores = 2)                    # number of cores
save(p1_norm_un, file = "./Stan/fits/pattern1_norm_un.rda")
```

```{r, stan}
load("./Stan/fits/pattern1_gamma_un.rda")
load("./Stan/fits/pattern1_norm_un.rda")
```

### Summary

#### Pattern 1

```{r, p1non}
params = names(p1_gamma_un)[grep("(alpha|beta)", names(p1_gamma_un))]

print(p1_gamma_un, params)
print(p1_norm_un, params)
```

### Coefficients of interest

#### Pattern 1

```{r, p1coefnon}
# Plot pattern beta coefficient with uncertainty
mcmc_areas(p1_gamma_un,
           pars = params[(length(params)-2):length(params)],
           prob = 0.95) + ggtitle("Posterior distributions",
                                  "with medians and 95% intervals") +
  scale_y_discrete(labels=c(
  "beta_int" = "Interaction", 
  "beta_sex" =  "Sex female",
  "beta_p" = "P1 in males")) + xlim(c(-50,20))

# Plot pattern beta coefficient with uncertainty
mcmc_areas(p1_norm_un,
           pars = params[(length(params)-2):length(params)],
           prob = 0.95) + ggtitle("Posterior distributions",
                                  "with medians and 95% intervals") +
  scale_y_discrete(labels=c(
  "beta_int" = "Interaction", 
  "beta_sex" =  "Sex female",
  "beta_p" = "P1 in males")) + xlim(c(-50,20))
```

### Patterns by sex

#### Pattern 1

```{r, p1patnon}
add_ci4int_bayes(p1_gamma_un)

add_ci4int_bayes(p1_norm_un)
```

#### All

```{r, all2}
add_ci4int_bayes(p1_gamma_un)[,1:3] %>% 
  rename(gamma = mean, gamma_se = se_mean) %>% 
  bind_cols(., normal = add_ci4int_bayes(p1_norm_un)[,2], normal_se = add_ci4int_bayes(p1_norm_un)[,3])
```
