---
title: "Linear fit"
subtitle: "Phthalates & phenols in M&N cohort"
author: "Lizzy Gibson"
date: "3/6/2021"
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 2
    code_folding: 'hide'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache=TRUE, autodep=TRUE, fig.align='center')
options(scipen = 999)
library(haven)
library(tidyverse)
library(janitor)
library(reshape2)
library(broom)
library(tableone)
library(xtable)
library(GGally)
library(gtsummary)
library(huxtable)
library(broom)
library(R.matlab)
library(MNdata) # Local package

library(mgcv)
library(splines)

source(here::here("/Users/lizzy/BN2MF/functions/fig_set.R"))
```

## M&N Data

* 5 phenols  
* 3 parabens  
* 9 phthalates  

```{r, read}
predictors = inner_join(mn_pht[,1:10], mn_phenol[,1:9], by = "SID") %>% drop_na()
iq = mn_outcome %>% dplyr::select(SID, WISC = WSC_CSFS_84)
mn_dat = predictors %>% left_join(., mn_demo, by = "SID") %>% left_join(., iq, by = "SID")
# 32 without WISC

ewa <- readMat(here::here("./Data/mn2_EWA.mat"))[[1]] %>% as_tibble() %>% rename(P2 = V1, P1 = V2)
mn_all = bind_cols(mn_dat, ewa)
```

## Distributions

### Chemicals

```{r, fig1, fig.height=10, fig.width=12}
mn_all %>% 
  pivot_longer(MEHHP:BPA) %>% 
  mutate(name = str_replace(name, "_", "-")) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(y = ..density..)) +
  facet_wrap(name~., scales = "free") + 
  labs(y = "Density", x="") +
  theme(axis.text.y = element_blank(),
        text = element_text(size = 30),
        axis.text.x = element_text(size = 10),
        axis.title.y = element_text(size = 35))
```

### Patterns

```{r, fig2}
mn_all %>% 
  pivot_longer(P1:P2) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(y = ..density..)) +
  facet_wrap(name~., scales = "free") + 
  labs(y = "Density", x="") +
  theme(axis.text.y = element_blank(),
        text = element_text(size = 30),
        axis.text.x = element_text(size = 10),
        axis.title.y = element_text(size = 30))
```

#### Logged

```{r, fig2}
mn_all %>% 
  pivot_longer(P1:P2) %>% 
  mutate(value = log(value)) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(y = ..density..)) +
  facet_wrap(name~., scales = "free") + 
  labs(y = "Density", x="") +
  theme(axis.text.y = element_blank(),
        text = element_text(size = 30),
        axis.text.x = element_text(size = 10),
        axis.title.y = element_text(size = 30))
```

## Scatterplots

```{r}
mn_all %>% 
  dplyr::select(SID, WISC, P1, P2) %>% 
  pivot_longer(P1:P2) %>% 
  ggplot(aes(x = value, y = WISC)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(.~name, scales = "free") 

mn_all %>% 
  dplyr::select(SID, WISC, P1, P2) %>% 
  pivot_longer(P1:P2) %>% 
  filter(value < 15) %>% 
  ggplot(aes(x = value, y = WISC)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(.~name, scales = "free") 
```

#### Logged

```{r, fig2}
mn_all %>% 
  dplyr::select(SID, WISC, P1, P2) %>% 
  pivot_longer(P1:P2) %>% 
  mutate(value = log(value)) %>% 
  ggplot(aes(x = value, y = WISC)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(.~name, scales = "free") 
```

## Predictors of outcome

```{r, predout}
#function to take exposure and outcome, regress, and output as tibble
regress_model <- function(out, pred) {

fit <- lm(get(out) ~ get(pred), data = mn_all)

stats <- tidy(fit) %>% bind_cols(., as_tibble(confint(fit))) %>% 
  mutate(predictor = pred,
         outcome = out) %>% 
  dplyr::select(-statistic) %>% 
  filter(term != "(Intercept)") %>% 
  bind_cols(., glance(fit) %>% 
  rename(model.p.value = p.value)) %>% 
  dplyr::select(predictor, outcome, everything(),
                -df.residual, -deviance, -logLik, -df, -statistic, -sigma, -term, -AIC, -BIC, -r.squared)

return(list(stats=stats, fit=fit))
}

#Create lists of exposures and outcomes
# WISC is the outcome here

# demographics and chemicals and patterns are exposures
demo = names(mn_demo)[2:10]

demo_wisc_models = tibble()
#loop through lm for each exposure/outcome combo
for (j in 1:length(demo)) {
  model_out <- regress_model("WISC", demo[j])$stats
  demo_wisc_models = bind_rows(demo_wisc_models, model_out)
}
```

### Demographical predictors

```{r}
demo_wisc_models %>% arrange(p.value)

summary(lm(WISC ~ HOME_SCORE + M_IQ + ALCOHOL + ETH + M_EDU +SEX+M_AGE+SMOKER_IN_HOME+MARITAL_STATUS, data = mn_all))
```

## Predictors of exposure

```{r}
# patterns are outcome here
patterns = c("P1", "P2")

# demographics are exposures

dem_pat_models = tibble()
#loop through lm for each exposure/outcome combo
for (i in 1:length(patterns)) {
  for (j in 1:length(demo)) {
  model_out <- regress_model(patterns[i], demo[j])$stats
  dem_pat_models = bind_rows(dem_pat_models, model_out)
  }
}
```

### Demographic predictors

```{r}
dem_pat_models %>% arrange(p.value)
```

### Logged outcome

```{r}
regress_outcome_log <- function(out, pred) {
  
fit <- lm(log(get(out)) ~ get(pred), data = mn_all)

stats <- tidy(fit) %>% bind_cols(., as_tibble(confint(fit))) %>% 
  mutate(predictor = pred,
         outcome = out) %>% 
  dplyr::select(-statistic) %>% 
  filter(term != "(Intercept)") %>% 
  bind_cols(., glance(fit) %>% 
  rename(model.p.value = p.value)) %>% 
  dplyr::select(predictor, outcome, everything(),
                -df.residual, -deviance, -logLik, -df, -statistic, -sigma, -term, -AIC, -BIC, -r.squared) 

  return(list(stats=stats, fit=fit))
}

# chemicals are outcome here
# demographics are exposures

ind_exp_logged = tibble()
#loop through lm for each exposure/outcome combo
for (i in 1:length(chem_pat)) {
  for (j in 1:length(demograph)) {
  model_out <- regress_outcome_log(chem_pat[i], demograph[j])$stats
  ind_exp_logged = bind_rows(ind_exp_logged, model_out)
  }
}

ind_exp_logged %>% filter(p.value < 0.10) %>% arrange(desc(outcome))
```

## Health models

```{r}
regress_health <- function(pred) {
  
fit <- lm(WISC ~ log(get(pred)) + M_IQ + ETH + ALCOHOL + M_EDU + MARITAL_STATUS + HOME_SCORE + SEX 
          # + SMOKER_IN_HOME + M_AGE
          , data = mn_all)

stats <- tidy(fit) %>% bind_cols(., as_tibble(confint(fit))) %>% 
  mutate(predictor = pred,
         outcome = "WISC") %>% 
  dplyr::select(-statistic) %>%
  slice(2) %>% 
  bind_cols(., glance(fit) %>% 
  rename(model.p.value = p.value)) %>% 
  dplyr::select(predictor, outcome, everything(), -std.error,
                -df.residual, -deviance, -logLik, -df, -statistic, -sigma, -AIC, -BIC, -r.squared, -term)

return(list(stats=stats, fit=fit))
}

health_models = tibble()
#loop through lm for each exposure/outcome combo
for (j in 1:length(chem_pat)) {
  model_out <- regress_health(chem_pat[j])$stats
  health_models = bind_rows(health_models, model_out)
  }
```

### Adjusted health models

```{r}
# Logged exposures
health_models %>% filter(p.value < 0.05)

health_models %>% filter(predictor %in% c("P1", "P2"))
```

#### Residuals

```{r, fig5, fig.height=3, fig.width = 9, results='hide'}
#loop through lm residual plots
for (j in 1:length(chem_pat)) {
  fit <- regress_health(chem_pat[j])$fit
  
  par(mfrow=c(1,4))
  print(plot(fit, which=1, col=c("blue"), main=paste0("Predictor: ", chem_pat[j])))
  print(plot(fit, which=2, col=c("blue"), main=paste0("Predictor: ", chem_pat[j])))
  print(plot(fit, which=3, col=c("blue"), main=paste0("Predictor: ", chem_pat[j])))
  print(plot(fit, which=5, col=c("blue"), main=paste0("Predictor: ", chem_pat[j])))
}
```

### Mutually adjusted patterns

```{r, mutadj}
fit_patterns <- lm(WISC ~ P1 + P2
                          #log(P1) + log(P2)
                          + M_IQ + ETH + ALCOHOL + M_EDU + MARITAL_STATUS + HOME_SCORE + SEX 
          + SMOKER_IN_HOME + M_AGE
          , data = mn_all)

tidy(fit_patterns) %>% bind_cols(., as_tibble(confint(fit_patterns))) %>% 
  dplyr::select(-statistic) %>%
  bind_cols(., glance(fit_patterns) %>% 
  rename(model.p.value = p.value)) %>% 
  dplyr::select(-df.residual, -deviance, -logLik, -df, -statistic, -sigma, -AIC, -BIC, -r.squared)
```

#### Residuals

```{r, fig6, fig.height=3, fig.width = 9, results='hide'}
#loop through lm residual plots
  par(mfrow=c(1,4))
  print(plot(fit_patterns, which=1, col=c("blue"), main="Mutually adjusted"))
  print(plot(fit_patterns, which=2, col=c("blue"), main="Mutually adjusted"))
  print(plot(fit_patterns, which=3, col=c("blue"), main="Mutually adjusted"))
  print(plot(fit_patterns, which=5, col=c("blue"), main="Mutually adjusted"))
```



## Other outcomes

```{r}
mn_other = left_join(mn_all, mn_bayley_wisc)
outcomes = names(mn_bayley_wisc)[8:12]
patterns = c("P1", "P2")

regress_other <- function(out, pred) {

fit <- lm(get(out) ~ get(pred) + I(get(pred)^2) + SEX + get(pred)*SEX +
            M_IQ + ETH + ALCOHOL + M_EDU + MARITAL_STATUS + HOME_SCORE, data = mn_other)

stats <- tidy(fit) %>% bind_cols(., as_tibble(confint(fit))) %>% 
  mutate(predictor = pred,
         outcome = out) %>% 
  slice(c(2:4,11)) %>% 
  dplyr::select(-statistic, -std.error) 
  # %>% 
  # bind_cols(., glance(fit) %>% 
  # rename(model.p.value = p.value)) %>% 
  # dplyr::select(predictor, outcome, everything(),
  #               -df.residual, -deviance, -logLik, -df, -statistic, 
  #               -sigma, -AIC, -BIC, -r.squared)

return(list(stats=stats, fit=fit))
}

other_outcomes = tibble()
#loop through lm for each exposure/outcome combo
for (i in 1:length(outcomes)) {
for (j in 1:length(patterns)) {
  model_out <- regress_other(outcomes[i], patterns[j])$stats
  other_outcomes = bind_rows(other_outcomes, model_out)
}
}

other_outcomes %>% arrange((p.value)) %>% print(n = 25)

other_outcomes %>% filter(grepl("PR", outcome)) %>% arrange((p.value))
```

```{r}
mn_other %>% 
  dplyr::select(SID, P1, P2, SEX, WISC) %>% 
  pivot_longer(P1:P2) %>% 
  ggplot(aes(x = value, color = SEX, fill = SEX)) +
  geom_point(aes(y = WISC), alpha=0.5) +
  geom_smooth(aes(y = WISC), method = "gam", formula = y ~ x + I(x^2)) +
  geom_histogram(aes(x=value), position = "identity", alpha = 0.5) +
  facet_wrap(.~name, scales = "free") +
  theme(legend.position = "bottom")

mn_other %>% 
  dplyr::select(SID, P1, P2, SEX, WSC_CSPR_84) %>% 
  pivot_longer(P1:P2) %>% 
  ggplot(aes(x = value, color = SEX, fill = SEX)) +
  geom_point(aes(y = WSC_CSPR_84), alpha=0.5) +
  geom_smooth(aes(y = WSC_CSPR_84), method = "gam", formula = y ~ x + I(x^2)) +
  geom_histogram(aes(x=value), position = "identity", alpha = 0.5) +
  facet_wrap(.~name, scales = "free") +
  theme(legend.position = "bottom")
```

```{r}
mn_female = mn %>% filter(SEX == "Female")

fit <- lm(WSC_CSPR_84 ~ P2 + I(P2^2) + P1 +
            M_IQ + ETH + ALCOHOL + M_EDU + MARITAL_STATUS + HOME_SCORE, data = mn_female)

get_output(fit)
```

