---
title: "Sensitivity Analyses"
subtitle: "Outliers and Missingness"
author: "Lizzy Gibson"
date: "6/21/2021"
output:
  html_document:
    toc: yes
    toc_float: yes

---

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align='center', cache=TRUE,
                      autodep = TRUE)

options(mc.cores = parallel::detectCores())
source("./source/read_data.R")

pal = brewer.pal(11, "RdBu")[c(2,4,11,10)]
```

```{r}
summary(mn$P1)
summary(whole_cc$P1)
```

## Outliers

We removed two outliers for the main analysis.

```{r}
# whole_cc = complete cases
# This is the model with outliers included
mod = lm(WISC ~ P1 + SEX*P1 + SEX + M_IQ + ALCOHOL + M_EDU  + M_AGE +
              MARITAL_STATUS + HOME_SCORE + mat_hard
             , data = whole_cc)
summary(mod)
plot(mod)

# Individual 272 influential based on Cooks distance, residual vs. leverage plot
ols_plot_cooksd_chart(mod)
ols_plot_resid_lev(mod)

# get rid of highest
whole_m1 = whole_cc[-which.max(whole_cc$P1),]
mod2 = lm(WISC ~ P1 + SEX*P1 + SEX + SEX + M_IQ + ALCOHOL + M_EDU  + M_AGE +
              MARITAL_STATUS + HOME_SCORE + mat_hard
             , data = whole_m1)
summary(mod2)
plot(mod2)

# cooks dist for 264
ols_plot_cooksd_chart(mod2)
ols_plot_resid_lev(mod2)
# Individual 264 influential based on Cooks distance, residual vs. leverage plot

grubbs.test(log(whole_cc$P1)) # highest values is an outlier
grubbs.test(log(whole_m1$P1))
```

### Viz

```{r}
# Fit the gam to whole data including outliers
fit_sense <- gam(WISC ~ s(P1, by = SEX) + SEX + M_IQ + ALCOHOL + M_EDU + 
                   MARITAL_STATUS + HOME_SCORE + M_AGE + mat_hard, 
                 data = whole_cc)
summary(fit_sense)

# get predicted values 
pred = as.data.frame(predict.gam(fit_sense, se.fit = T, type="terms"))

# Create a dataframe to predict for females
const = tibble(P1 = seq(min(whole_cc$P1), max(whole_cc$P1), length=289)) %>% 
  mutate(SEX = "Females",
         M_IQ = 0, 
         ALCOHOL = as_factor("No"),
         M_EDU = "≥ High school degree or equivalent", 
         M_AGE = 0, 
         mat_hard = "No",
         MARITAL_STATUS = "Never Married", 
         HOME_SCORE = 0)

pred_f = as.data.frame(predict.gam(fit_sense, newdata = const, se.fit = T, type="terms"))

# This gets smooth CI for females
sense_f = as_tibble(pred_f) %>% 
  bind_cols(., const) %>% 
  dplyr::select(grep("(SEX|P1)", names(.))) %>%
  mutate(predIQ = mean(whole_cc$WISC) + fit.SEX + fit.s.P1..SEXMales + fit.s.P1..SEXFemales,
         se= se.fit.SEX + se.fit.s.P1..SEXMales + se.fit.s.P1..SEXFemales,
         lci = predIQ - 1.96*se,
         uci = predIQ + 1.96*se) %>% 
  mutate(model = "Sensitivity") %>% 
  dplyr::select(-grep("fit", names(.)))

# combine and create CI
sense_all = whole_cc %>%
  bind_cols(., pred) %>% 
  mutate(extreme = ifelse(SID %in% c(1209, 1229), "Yes", "No")) %>% 
  dplyr::select(WISC, grep("(SEX|P1)", names(.)), extreme) %>% 
  mutate(predIQ = mean(WISC) + fit.SEX + fit.s.P1..SEXMales + fit.s.P1..SEXFemales,
         se= se.fit.SEX + se.fit.s.P1..SEXMales + se.fit.s.P1..SEXFemales,
         lci = predIQ - 1.96*se,
         uci = predIQ + 1.96*se,
         model = "Sensitivity") %>% 
  dplyr::select(-grep("fit", names(.)))

# Just whole data
sense_all %>% 
  ggplot(aes(x = P1, group = interaction(SEX, model),fill = interaction(SEX, model))) +
  geom_point(aes(y = WISC), alpha=0.25, color="grey") +
  geom_point(aes(y = WISC), color="black",
             data = subset(sense_all, extreme =="Yes")) +
  geom_ribbon(aes(ymin = lci,
                  ymax = uci), 
              alpha = 0.5, data = subset(sense_all, SEX == "Males")) +
  geom_line(aes(y = predIQ),
            data = subset(sense_all, SEX == "Males")) + 
  geom_ribbon(aes(ymin = lci,
                  ymax = uci), 
              alpha = 0.5, data = sense_f) +
  geom_line(aes(y = predIQ), data = sense_f) +
  facet_grid(.~SEX, scales = "free_x") +
  labs(y = "WISC Full Scale IQ", x = "Pattern 1 concentration") +
  theme(legend.title = element_blank())

# Main ####
# Flipping gets predicted values for females
main_flip <- lm(WISC ~ P1 + SEX*P1 + SEX + M_IQ + ALCOHOL + M_EDU  + M_AGE +
                 MARITAL_STATUS + HOME_SCORE + mat_hard
               , data = mn_flip)

# this gets predicted values for males
main_fit <- lm(WISC ~ P1 + SEX*P1 + SEX + M_IQ + ALCOHOL + M_EDU  + M_AGE +
                MARITAL_STATUS + HOME_SCORE + mat_hard
              , data = mn)

summary(main_fit)
summary(main_flip)

# Get predicted values
# this is conditional on everything else!
pred_main = as.data.frame(predict(main_fit, se.fit = TRUE, type = c("terms")))

# Get predicted values for females
pred_flip = as.data.frame(predict(main_flip, se.fit = TRUE, type = c("terms")))

# Combine predicted outcomes with data
# And make CI
main = 
  mn_subset %>%
  bind_cols(., pred_main) %>% 
  bind_cols(., flip.se = (pred_flip$se.fit.P1 + pred_flip$se.fit.P1.SEX)) %>% # just get se for female
  dplyr::select(SID, WISC, grep("(SEX|P)", names(.)), flip.se) %>% 
  mutate(SEX = str_c(SEX, "s"),
         predIQ = fit.P1 + mean(WISC) + fit.SEX + fit.P1.SEX, # ifelse(SEX == "Female", predIQf, predIQm),
         se.male = se.fit.P1 + se.fit.P1.SEX,
         se.female = flip.se,
         se = ifelse(SEX == "Females", se.female, se.male),
         lci = predIQ - 1.96*se,
         uci = predIQ + 1.96*se) %>% 
  dplyr::select(-grep("fit", names(.))) %>% 
  mutate(model = "Main")

# Main model fits
main %>% 
  ggplot(aes(x = P1)) +
  geom_point(aes(y = WISC), color = "lightgray", size = 0.5) + 
  geom_abline(intercept = mean(main$WISC), slope = 0, 
              color = "darkgray", linetype = "dashed") + 
  geom_line(aes(y = predIQ)) +
  geom_ribbon(aes(ymin = lci, ymax = uci),
              alpha = 0.25, linetype = "dotted", size = 0.25) +
  facet_grid(.~SEX, scales = "free_x") +
  ylim(45, 135) +
  theme_minimal(base_size = 15) + 
  theme(legend.title = element_blank(),
        legend.position = "none") +
  scale_color_lancet() + scale_fill_lancet() +
  labs(y = "WISC full scale IQ", x = "PHT pattern concentration") 

# Final plot ####
sense_plot = bind_rows(sense_all, main)

# Figure S1
sense_plot %>% 
  ggplot(aes(x = P1, group = model, fill = model)) +
  geom_point(aes(y = WISC), alpha=0.25, color="grey") +
  geom_point(aes(y = WISC), color="black",
             data = subset(sense_plot, extreme =="Yes")) +
  geom_line(aes(y = predIQ, color = model), data = sense_f) +
  geom_ribbon(aes(ymin = lci,
                  ymax = uci),
              alpha = 0.5, data = sense_f) +
  geom_ribbon(aes(ymin = lci,
                  ymax = uci), alpha = 0.5,
              data = filter(sense_plot, SEX == "Males" | model == "Main")) +
  geom_line(aes(y = predIQ, color = model),
            data = subset(sense_plot, SEX == "Males" | model == "Main")) +
  facet_grid(.~SEX, scales = "free_x") +
  labs(y = "WISC Full Scale IQ", x = "Pattern 1 concentration") +
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 15)) + scale_fill_nejm() + scale_color_nejm()
```

## Missingness

```{r}
model_dat = whole %>% 
  filter(!is.na(WISC)) %>% 
  dplyr::select(-c(SID, GEST, WISC_VC, WISC_PR, WISC_PS, WISC_WM, P2))

model_dat %>% names()

model_dat %>% ff_glimpse()

mice::md.pattern(model_dat, rotate.names = T)
# 289 complete samples
# 14 missing only home score
# 6 missing only maternal iq
# 2 missing both

aggr(model_dat, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, 
     labels=names(model_dat), cex.axis=.7, gap=3, ylab=c("Histogram of missing data","Pattern"))

marginplot(model_dat[c(6,9)])

explanatory = c("ETH","M_EDU","MARITAL_STATUS","SMOKER_IN_HOME","SEX","HOME_SCORE",
                "ALCOHOL","M_AGE","mat_hard","WISC","P1")

model_m = model_dat %>% 
  mutate(home_miss = as_factor(ifelse(is.na(HOME_SCORE), 1, 0)),
         iq_miss = as_factor(ifelse(is.na(M_IQ), 1, 0)))

model_m %>% missing_compare(., dependent = "M_IQ", explanatory)

explanatory = c("ETH","M_EDU","MARITAL_STATUS","SMOKER_IN_HOME","SEX","M_IQ",
                "ALCOHOL","M_AGE","mat_hard","WISC","P1")

model_m %>% missing_compare(., dependent = "HOME_SCORE", explanatory) 
```

## Regular OLS

```{r}
mn_phenol[,1:9]
mn_pht[,1:10]

all_dat = mn %>% inner_join(mn_phenol[,1:9]) %>% inner_join(mn_pht[,1:10])
all_dat

full_reg <- lm(WISC ~ MEHHP + MECPP + MEOHP+ MEHP + MCPP + MIBP +  MBP +  MBZP + MEP +
                      BP_3  +  B_PB + M_PB + P_PB  +  TCS + DCP_24 + DCP_25 +  BPA +
                      SEX + M_IQ + ALCOHOL + M_EDU + M_AGE + MARITAL_STATUS + HOME_SCORE + mat_hard
             , data = all_dat)

tidy_ci(full_reg) %>% select(-std.error, -statistic) %>% .[2:18,]
```

## Groupwise averages

```{r}
scaled_dat = all_dat %>% 
  mutate_at(vars(20:36), function(x) x/sd(x)) %>% 
  mutate(pht = (MEHHP + MECPP + MEOHP+ MEHP + MCPP + MIBP +  MBP +  MBZP + MEP)/9,
         phenol = (BP_3  +  B_PB + M_PB + P_PB  +  TCS + DCP_24 + DCP_25 +  BPA)/8)

group_reg <- lm(WISC ~ pht + phenol + SEX +
                  pht*SEX + phenol*SEX +
                  M_IQ + ALCOHOL + M_EDU + M_AGE + MARITAL_STATUS + HOME_SCORE + mat_hard
             , data = scaled_dat)

tidy_ci(group_reg) %>% select(-std.error, -statistic)

add_ci4interaction_both(group_reg, term1 = "pht", interaction1 = "pht:SEXFemale", term2 = "phenol", interaction2 = "phenol:SEXFemale")
```

## PCA
```{r}
just_edc = scaled_dat[,20:36]

pca_out = prcomp(just_edc)
plot(pca_out)

sum((pca_out$sdev^2/sum(pca_out$sdev^2))[1:4])

rotation <- as.data.frame.matrix(pca_out$rotation) ## rotation is the loadings variable within the pca output.
rotation$chem <- row.names(rotation)
rotation

rotation %>% 
  pivot_longer(1:17)  %>% 
  filter(name %in% c("PC1", "PC2", "PC3", "PC4")) %>% 
  ggplot(aes(x = chem, y = value)) + geom_col() +
  facet_wrap(~ name) + theme_bw() + 
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust = 1),
        strip.background = element_rect(fill = "white")) +
  geom_hline(yintercept = 0, size = 0.2) +
  labs(x = "Chemicals",
       y = "Loadings")
```

```{r}
pca_dat = scaled_dat %>% bind_cols(pca_out$x %>% as_tibble())

pca_reg <- lm(WISC ~ SEX + PC1 + PC2 + PC3 + PC4 +
                  M_IQ + ALCOHOL + M_EDU + M_AGE + MARITAL_STATUS + HOME_SCORE + mat_hard
             , data = pca_dat)

tidy_ci(pca_reg) %>% select(-std.error, -statistic)
```

