---
title: "Phthalate & phenol exposure patterns"
subtitle: "& child intelligence in M&N cohort"
author: "Lizzy Gibson"
date: "3/16/2021"
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align='center')

source("./source/read_data.R")
```

## Mothers & Newborns

* 5 phenols  
* 3 parabens  
* 9 phthalates  

## Demographics

```{r, demo}
# Ran BN2MF on this subset
ppp_343 = left_join(ppp_cov, mn_outcome) %>% mutate(Subsample = "BN2MF Subsample") %>% rename(HOME_SCORE = HOMETOT)

# this subset had WISC measured
ppp_311 = ppp_343 %>% filter(!is.na(WISC)) %>% mutate(Subsample = "WISC Subsample")

# this subset had all covariates measured
ppp_289 = ppp_311 %>% filter(!is.na(M_IQ) & !is.na(HOME_SCORE)) %>% mutate(Subsample = "Complete Cases")

# whole cohort is 727 mothers
cohort = mn_demo %>% 
        left_join(., mn_outcome, by = "SID") %>% 
        mutate(Subsample = "Entire Cohort") %>% 
        rename(HOME_SCORE = HOMETOT)

demo =  bind_rows(cohort, ppp_343, ppp_311, ppp_289) %>% 
        mutate_at(vars(SMOKER_IN_HOME, SEX, ALCOHOL), as_factor) %>% 
        dplyr::select(ETH, M_AGE, M_EDU, M_IQ, HOME_SCORE, mat_hard, MARITAL_STATUS, ALCOHOL, SMOKER_IN_HOME, 
                      SEX, WISC, Subsample) %>% 
        rename(Ethnicity = ETH,
               `Maternal education` = M_EDU,
               `Marital status` = MARITAL_STATUS,
               `Child sex` = SEX,
               `HOME scale` = HOME_SCORE,
               `Maternal IQ` = M_IQ,
               `Maternal age at delivery` = M_AGE,
               `Prenatal alcohol consumption` = ALCOHOL,
               `Smoker in home` = SMOKER_IN_HOME,
               `Material hardship` = mat_hard,
               `Child Full Scale IQ` = WISC) %>% 
        mutate(Subsample = fct_inorder(Subsample))
```

## Table 1

```{r one}
demo %>%  
  filter(Subsample == "BN2MF Subsample") %>% 
  tbl_summary(missing = "no",
              statistic = list(all_continuous() ~ "{mean} ({sd})")) %>% 
              as_gt() %>% 
        tab_header(title = "Subject demographics and distribution of potential confounders, model covariates, and outcome variable")

# demo %>% filter(Subsample == "Study Population") %>%
#          tbl_summary(missing = "no", digits = list(all_continuous() ~ 1,
#                                                    all_categorical() ~ 1),
#          statistic = list(all_continuous() ~ "{mean} & {sd}",
#                           all_categorical() ~ "{n} & {p}")) %>%
#         as_kable_extra(., format = "latex")
# ^ print to latex
```

### Supplemental table 1
```{r}
demo %>% 
  tbl_summary(by = Subsample, missing = "no", 
                     statistic = list(all_continuous() ~ "{mean} ({sd})")) %>% add_p() 

# demo %>%
#          tbl_summary(by = Subsample,
#            missing = "no", digits = list(all_continuous() ~ 1,
#                                          all_categorical() ~ 1),
#          statistic = list(all_continuous() ~ "{mean} & {sd}",
#                           all_categorical() ~ "{n} & {p}")) %>% add_p() %>%
#          as_kable_extra(., format = "latex")

# ^^ supplemental table 
```

## Distributions \& dectection

```{r, lod}
# mn_phenol and mn_pht are datasets I have stored internally in a package
lod <- mn_phenol %>% drop_na(BP_3:BPA) %>% 
          rename(B_PB_detect = B_PB_LOD_0_2, TCS_detect = TCS_LOD_2_3, 
                DCP_24_detect = X24_DCP_LOD_0_2, BP_3_detect = BP_3_LOD_0_4) %>%   
          mutate_at(vars(10:13), ~ifelse(is.na(.), 0, 1)) %>% # 1 if detected, 0 otherwise
          inner_join(., mn_pht, by = "SID") %>% 
  dplyr::select(grep("detect", colnames(.))) %>%
  gather(chem, level) %>% 
  mutate(level = ifelse(level > 1, 0, level)) %>% 
  group_by(chem, level) %>% 
  summarize(n = n()) %>% 
  spread(level, n) %>% 
  mutate_all(~replace_na(., 0))
# Number of obs with each flag for each pht
# 14 bc 3 detected 100%

detected <- lod %>% 
  mutate(Prop_Detected = `0`/(`1` + `0`),
         `% <LOD` = 1 - Prop_Detected) %>%
  ungroup() %>% 
  dplyr::select(Chemical = chem, `% <LOD`) %>% 
  mutate(Chemical = str_remove(Chemical, "_detect")) %>% 
  rbind(., tibble(Chemical = "M_PB",   `% <LOD` = 0)) %>% # add the three detected 100% 
  rbind(., tibble(Chemical = "P_PB",   `% <LOD` = 0)) %>% 
  rbind(., tibble(Chemical = "DCP_25", `% <LOD` = 0))

conc = mn_ppp %>% # get summary stats for concentrations
  pivot_longer(MEHHP:BPA,
               names_to = "Chemical") %>% 
  group_by(Chemical) %>% 
  summarise(Mean = mean(value, na.rm = TRUE),
            Stdev = sd(value, na.rm = TRUE),
            Min = min(value, na.rm = TRUE),
            qs = quantile(value, c(0.25, 0.5, 0.75), na.rm = TRUE), prob = c("Q25", "Median", "Q75"),
            Max = max(value, na.rm = TRUE)) %>% 
  pivot_wider(names_from = "prob",
              values_from = "qs") %>% 
  dplyr::select(Chemical:Min, Q25:Q75, Max)

ppp_table <- left_join(detected, conc, by = c("Chemical")) %>% 
  # combine concentrations and detection into table
  mutate(`% <LOD` = `% <LOD` * 100) %>% 
  mutate_if(is.numeric, round, digits = 4) %>% 
  mutate(group = case_when(Chemical == "M_PB" ~ "phenols",
                           grepl("^M", Chemical) ~ "phthalates",
                           TRUE ~ "phenols")) %>% 
  arrange(group, Chemical) %>% 
  dplyr::select(-group)
```

## Table 2
```{r}
ppp_table %>% knitr::kable(caption = "Distribution of phathlate metabolites & phenols (ng/ml) in maternal spot urine during the third trimester of pregnancy (n = 343)")

ppp_table %>%
  dplyr::select(1:2, 6:8) # %>%
#   stargazer::stargazer(summary = F)
# ^ print to latex

ewa_raw %>% 
  summarise_all(quantile, probs = seq(0.25, 0.75, 0.25)) %>% bind_cols(probs = seq(0.25, 0.75, 0.25), .)
# added this to table
```

### Chemicals

```{r, fig1, fig.height=10, fig.width=12}
mn_ppp %>% 
  pivot_longer(MEHHP:BPA) %>% 
  mutate(name = str_replace(name, "_", "-")) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(y = ..density..), alpha=0.65, fill = "#0072B5") +
  facet_wrap(name~., scales = "free") + 
  labs(y = "Density", x="") +
  theme(axis.text.y = element_blank(),
         axis.text.x = element_text(size = 10))
```

### Correlation

```{r, fig.height=7, fig.width=7}
cormat <- get_lower_tri(round(cor(mn_ppp[,-1], use = "complete.obs", 
                                  method = c("spearman")),2))[2:17, 1:16]

melted_cormat <- melt(cormat) %>% 
  rename(Correlation = value) %>% 
  mutate(Var1 = case_when(Var1 == "DCP_24" ~ "24-DCP",
                          Var1 == "DCP_25" ~ "25-DCP",
                          Var1 == "BP_3" ~ "BP-3",
                          TRUE ~ as.character(Var1)),
         Var2 = case_when(Var2 == "DCP_24" ~ "24-DCP",
                          Var2 == "DCP_25" ~ "25-DCP",
                          Var2 == "BP_3" ~ "BP-3",
                          TRUE ~ as.character(Var2)),
    Var1 = fct_inorder(str_remove(Var1, "_")),
    Var2 = fct_inorder(str_remove(Var2, "_"))) %>% as_tibble()
```

## Figure 1a
```{r}
#pdf("./Figures/ppp_corr.pdf")
melted_cormat %>% 
  mutate(Var1 = fct_rev(Var1)) %>% 
  ggplot(aes(x = Var2, y = Var1)) + 
  geom_tile(aes(fill = Correlation), color = "black", size=0.25) + 
  scale_fill_gradient2(low = "#046C9A", mid = "beige", high = "#F21A00",
                       na.value = "grey90") +
  #scale_fill_distiller(palette="RdYlBu",
  #                     na.value = "grey90") +
  labs(x = "", y = "", title = "") + 
  theme_test(base_size = 20) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 15),
        legend.position = "bottom")
#dev.off()
```

## Exposure patterns

### Loadings
```{r, load-load}
applied <- eh %>% 
  as_tibble() %>% 
  mutate(Pattern = 1:2) %>% 
  gather(key = Chemicals, value = Loadings, -Pattern) %>%
  mutate(Class = as_factor(case_when(grepl("PB", Chemicals) ~ "Parabens",
                           grepl("^M[A-Z]", Chemicals) ~ "Phthalates",
                           TRUE ~ "Phenols")),
         Chemicals = str_replace(Chemicals, "_", "-")) %>% 
  mutate(Pattern = paste0("Pattern ", Pattern),
         Chemicals = fct_inorder(Chemicals))
```

## Figure 1b
```{r}
#pdf("./Figures/eh_loadings.pdf", width = 2.5)
applied %>% 
  mutate(Chemicals = fct_rev(Chemicals)) %>% 
  ggplot(aes(x = Pattern, y = Chemicals)) + 
  geom_tile(aes(fill = Loadings), color = "black", size=.25) + 
  scale_fill_gradient2(low = "#046C9A", mid = "beige", high = "#F21A00") +
  labs(x = "", y = "", title = "") + 
  theme_test(base_size = 20) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 15),
        panel.grid.major = element_blank(),
        legend.direction = "horizontal",
        legend.position = c(0, -0.275), # c(1,0) right bottom, c(1,1) right top.
        legend.background = element_rect(fill = "#ffffffaa", colour = NA),
        #legend.key.size = unit(0.85, "lines"),
        plot.margin = margin(0,1,1,0, "cm"))
#dev.off()
```

### Distributions

```{r, figpc, fig.height=7}
ewa %>% 
  pivot_longer(P1:P2) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(y = ..density..), alpha=0.65, fill = "#0072B5") +
  facet_wrap(name~., scales = "free") + 
  labs(y = "Density", x = "")

bind_cols(ppp_343, ewa) %>% 
  mutate(SEX = fct_relevel(SEX, "Male", after = 1)) %>% 
  pivot_longer(P1:P2) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(y = ..density.., fill = SEX), alpha = 0.65, position = "identity") +
  facet_wrap(name~., scales = "free") + 
  labs(y = "Density", x="")
```

## Health models

### Unadjusted

```{r}
fit_p1 <- lm(WISC ~ P1 + SEX + SEX*P1, data = mn)
add_ci4interaction(fit_p1, "P1", "P1:SEXFemale")

fit_p2 <- lm(WISC ~ P2 + SEX + SEX*P2, data = mn)
add_ci4interaction(fit_p2, "P2", "P2:SEXFemale")
```

```{r}
p2_non <- gam(WISC ~ s(P2, by = SEX), data = mn)
summary(p2_non)
par(mfrow = c(1,2))
plot(p2_non)
par(mfrow = c(1,1))
```

```{r}
mn %>% 
  ggplot(aes(x = P2, y = WISC, color = SEX)) + geom_point() + geom_smooth()
```

### Adjusted

#### Pattern 1

```{r}
fit_p1a <- lm(WISC ~ P1 + SEX*P1 + SEX + M_IQ + ALCOHOL + M_EDU  + M_AGE +
              MARITAL_STATUS + HOME_SCORE + mat_hard
             , data = mn)

add_ci4interaction(fit_p1a, "P1", "P1:SEXFemale")
glance(fit_p1a)[,-c(11:12)]
```

#### Pattern 2

```{r}
fit_p2a <- lm(WISC ~ P2 + SEX*P2 + SEX + M_IQ + ALCOHOL + M_EDU + M_AGE +
              MARITAL_STATUS + HOME_SCORE + mat_hard
             , data = mn)
add_ci4interaction(fit_p2a, "P2", "P2:SEXFemale")
glance(fit_p2a)[,-c(11:12)]
```

## Table 3

```{r}
tabp1 = add_ci4interaction(fit_p1a, "P1", "P1:SEXFemale")[c(2,11:12),] %>% mutate(pattern = "Pattern 1")
tabp2 = add_ci4interaction(fit_p2a, "P2", "P2:SEXFemale")[c(2,11:12),] %>% mutate(pattern = "Pattern 2")

model_table = bind_rows(tabp1, tabp2)[,c(1:2, 6:8)] %>% mutate(model = "Traditional") %>% 
  dplyr::select(model, pattern, everything()) %>% 
  arrange(model, pattern, term) %>% 
  mutate_if(is.numeric, round, 1) %>% 
  mutate(`95% Confidence Interval` = str_c("(", `2.5 %`, ", ", `97.5 %`, ")")) %>% 
  mutate(term = case_when(term == "sex*p" | grepl("SEX", term) ~ " interaction term",
                          TRUE ~ term),
         term = str_remove(term, "(P1|P2|p)"),
         term = str_c(pattern, term)) %>% 
    dplyr::select(-`2.5 %`, -`97.5 %`, -pattern)
model_table

# health model table
# stargazer::stargazer(model_table, summary = F)
```
